### ISSUE TITLE
Switch to gradle

### ISSUE THREAD

**Issue by nedtwigg** [tombousso/sJava#1]
IMO gradle is a really great way to help people try your project.  It includes `gradlew.bat` and `gradlew` (a unix-compatible shell script), so that just about anyone on any system can just run `gradlew example` without having to set anything up.

It would also let you remove the jars from your `lib` directory, and download them as dependencies.

Very cool project!

**Comment by tombousso** [comment]
Thanks for the suggestion.

I decided that Gradle is indeed more suitable than Make.
I've replaced the Makefiles with Gradle build scripts and added the `gradlew` wrapper.

I also updated the walkthrough in the README.
